default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV.fetch("POSTGRES_DB") { "ecsite00" } %>"
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
 database: <%= ENV.fetch("POSTGRES_DB") { "ecsite00" } %>_development

test:
  <<: *default
 database: <%= ENV.fetch("POSTGRES_DB") { "ecsite00" } %>_test

production:
 <<: *default
 database: <%= ENV.fetch("POSTGRES_DB") { "ecsite00" } %>_production